[package]
name = "fetrust"
version = "0.1.1"
edition = "2021"
description = "fetchtool in rust"
categories = ["os","fetching","system","device"]
license = "GPL-3.0"

[dependencies]
figlet-rs = "0.1.4"
ansi_term = "0.12.1"
tinyrand = "0.5"
tinyrand-std = "0.5"
another_json_minimal = "0.0.2"
