name: Release Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'Cargo.toml'
      - 'src/**'

  pull_request:
    branches:
      - main
    paths:
      - 'Cargo.toml'
      - 'src/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          cargo build --release

      - name: Bump version if changed
        id: version
        run: |
          # Assuming the version is in Cargo.toml, adjust if using package.json or others
          current_version=$(grep -oP 'version\s*=\s*"\K[0-9\.]+' Cargo.toml)
          echo "Current version: $current_version"
          echo "version=$current_version" >> $GITHUB_ENV

      - name: Upload build artifacts
        if: steps.version.outputs.version != ''
        uses: actions/upload-artifact@v4
        with:
          name: fetrust-${{ env.version }}  # Artifact name, can include version
          path: target/release/fetrust  # Path to your compiled binary or other build artifacts
         
