name: Release Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'Cargo.toml'
      - 'src/**'

  pull_request:
    branches:
      - main
    paths:
      - 'Cargo.toml'
      - 'src/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          cargo build --release

      - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Binary Release"
          files: target/release/fetrust