name: Build and Release Rust Binary

on:
  release:
    types: [published]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --release

  # Check formatting with rustfmt
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

      - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: target/release/fetrust
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
