name: Build and Release Rust Binary

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: nightly

    - name: Build with cargo
      run: cargo build --release

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: target/release/fetrust
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}